/* ============================================================
   Shared trilingual content (EN / RU / UK) for all SOLUTIONS
   style variants. Each variant page includes this file and reads
   window.SITE_CONTENT. Keep copy here so variants never drift.
   (The cinematic `sections[].extras` markup is ОБСИДИАН-specific;
    variants that don't use it can ignore it.)
============================================================ */
(function () {
  const capsHTML = arr => `<div class="extras">${arr.map(c => `<span class="cap ${c[1] || ''} reveal-extra"><span class="dot"></span>${c[0]}</span>`).join('')}</div>`;
  const ctaHTML = t => `<div class="ctaWrap">
      <button class="cta" id="cta">${t.cta} <span class="arr">→</span></button>
      <a class="ghost" href="#">${t.cases}</a>
      <span class="micro">${t.micro}</span>
      <button class="toSite" id="toSite">${t.more} <span class="chev">↓</span></button></div>`;

  const CONTENT = {
    en: {
      htmlLang:'en',
      title:'SOLUTIONS — Turnkey Digital Solutions | Websites, Apps, Automation',
      desc:'We turn scattered processes into one digital solution — turnkey. Websites, web apps, automation and integrations. Fixed price. Free audit and a plan in 3 days.',
      hint:'scroll',
      rail:['Chaos','Foundation','Transformation','Price','Start'],
      sections:[
        {kicker:'Turnkey digital solutions', headline:'Build your <span class="grad">system</span> from chaos',
         sub:'Scattered processes, spreadsheets and services — into one digital solution. Turnkey, without you touching the tech.', extras:''},
        {kicker:'Turnkey — full cycle', headline:'Set the goal — we <span class="grad">build the foundation</span>',
         sub:'Audit, architecture, design, development, launch and support — the whole cycle on us. You get a finished working product, not a pile of parts.',
         extras:capsHTML([['Audit'],['Design'],['Launch']])},
        {kicker:'Digital transformation', headline:'We rebuild the <span class="grad">business</span>, not patch holes',
         sub:'We automate routine and connect systems and data into one loop. We change how the company works — not bolt software onto the old way.',
         extras:`<div class="extras"><div class="stat reveal-extra"><div><div class="num">×3</div><div class="lbl">faster processes</div></div><div><div class="num">−40%</div><div class="lbl">operating costs</div></div></div></div>`},
        {kicker:'Affordable & transparent', headline:'Premium result <span class="grad">without the premium bill</span>',
         sub:'No bloated estimates or hidden hours. A modular approach and a fixed turnkey price — you pay for the result.',
         extras:`${capsHTML([['Fixed price','c'],['Modular','b']])}<p class="proof reveal-extra">Built for <b>your market</b>: local integrations, language and specifics — custom, not a template.</p>`},
        {kicker:'Ready to start', final:true, headline:'Your system is <span class="grad">assembled</span>. Launch?',
         sub:'A free diagnostic and a transformation plan in 3 days. We’ll show how your chaos becomes a turnkey solution.',
         extras:ctaHTML({cta:'Get a plan in 3 days',cases:'See examples',micro:'Free. No obligations.',more:'Services, pricing & examples'})}
      ],
      nav:{services:'Services',pricing:'Pricing',faq:'FAQ',wa:'Message on WhatsApp'},
      site:{
        services:{eyebrow:'What we do', h2:'Turnkey digital solutions <span class="grad">— idea to launch</span>',
          lead:'We take the whole cycle on us: you get a finished working product, not a list of tasks. Fixed price, no hidden hours.',
          cards:[['🌐','Websites & landings','Selling websites turnkey: design, development, launch and analytics.'],
                 ['⚙️','Web apps & SaaS','Dashboards, portals and SaaS products from scratch — to your business logic.'],
                 ['🔄','Process automation','We remove manual routine and spreadsheets — processes in one system, no chaos.'],
                 ['🔌','Integrations','We connect CRM, ERP, payments, messengers and services into one loop.'],
                 ['🤖','Bots & AI','Telegram and chat bots, AI assistants and LLM-based automation.'],
                 ['🛠️','Support & growth','We maintain, improve and scale the product after launch.']]},
        process:{eyebrow:'How we work', h2:'A transparent path <span class="grad">to the result</span>',
          lead:'No uncertainty: you know the scope, timeline and price up front.',
          steps:[['01 — FREE','Audit','We break down the task, processes and goal. We find where time and money leak.'],
                 ['02','Estimate & plan','Fixed price and timeline. A transformation plan in 3 days.'],
                 ['03','Development','Design → development → testing. We show progress at every step.'],
                 ['04','Launch & support','We deploy, train the team, maintain and grow.']]},
        pricing:{eyebrow:'Pricing', h2:'Premium result <span class="grad">without the premium bill</span>',
          lead:'A modular approach and a fixed turnkey price — you pay for the result. Exact price after a free audit.',
          items:[{name:'Pilot / MVP',amt:'from&nbsp;$1,500',small:'',desc:'A fast start: the key feature in 2–3 weeks. We validate the idea on real users.',li:['Key feature','Clean design','Launch in 2–3 weeks'],btn:'Discuss a pilot',pkg:'Pilot / MVP'},
                 {name:'Turnkey project',amt:'from&nbsp;$4,900',small:'',desc:'A full solution: audit → design → development → launch. We take the whole cycle.',li:['Audit & strategy','Design + development','Integrations to fit','Launch & training'],btn:'Get an estimate',pkg:'Turnkey project',feat:true,tag:'Popular'},
                 {name:'Support',amt:'from&nbsp;$500',small:'/mo',desc:'Growth, improvements and maintenance after launch. We respond fast.',li:['Improvements & features','Monitoring & fixes','Priority contact'],btn:'Discuss support',pkg:'Support'}],
          note:'💡 Not sure which package you need? Start with a <b>free audit</b> — we’ll name the exact price for your task.'},
        why:{eyebrow:'Why us', h2:'A partner, <span class="grad">not a contractor</span>',
          items:[['🔑','Turnkey','We take the whole cycle — from audit to support. You don’t touch the tech.'],
                 ['💸','Fixed price','No bloated estimates or hidden hours. You pay for the result.'],
                 ['⚡','Start in 3 days','A free audit and transformation plan — this week.'],
                 ['🌍','Worldwide','Remote-first delivery, your timezone and language — custom, not a template.'],
                 ['🧩','Any task','Websites, apps, automation, integrations, bots and AI — in one place.'],
                 ['🤝','In touch','Transparent progress and fast answers at every step.']]},
        cases:{eyebrow:'What we deliver', h2:'Examples of <span class="grad">turnkey work</span>',
          lead:'Typical projects we take on. Real cases are added as we launch — a chance to be the first at a discount.',
          cards:[['📊','Sales automation','CRM + integrations + reporting. Less manual work, a transparent pipeline.'],
                 ['🚀','Online product launch','From idea to a working website or app, turnkey — fast and affordable.'],
                 ['🗂️','Process digitization','Accounting, requests and documents in one system instead of scattered spreadsheets.']]},
        faq:{eyebrow:'Questions', h2:'The <span class="grad">essentials</span>',
          qa:[['How much does it cost?','From $1,500 for a pilot. We name the exact price after a free audit — fixed, no hidden hours.'],
              ['What are the timelines?','Pilot — 2–3 weeks. Turnkey project — from 4–8 weeks depending on scope. Timelines are fixed in the estimate.'],
              ['What does “turnkey” mean?','We take the whole cycle: audit, design, development, launch and support. You don’t need to touch the tech — you get a finished result.'],
              ['What if I already have something?','We’ll plug into your current solution, run an audit and improve or rebuild what holds you back.'],
              ['Are revisions included?','Yes, within the agreed scope. Changes beyond it — a separate transparent estimate, no surprises.'],
              ['Do you work under a contract / NDA?','Yes. Contract and NDA on request. Everything transparent and official.']]},
        contact:{eyebrow:'Ready to start', h2:'A free audit and plan <span class="grad">in 3 days</span>',
          lead:'We’ll show how your chaos becomes a turnkey solution. Free, no obligations.',
          chips:['⚡ Reply within a day','🔒 Confidential','💸 Fixed price'],
          ph:{name:'Your name',contact:'Phone or @handle',task:'Briefly about your task (optional)'},
          submit:'Message on WhatsApp', altPre:'or by email: ', altLink:'send a message',
          micro:'Clicking opens a chat with a ready message — nothing is sent without you.'},
        footer:{tagline:'Turnkey digital solutions · © 2026', wa:'WhatsApp', email:'Email', top:'Top ↑'}
      },
      waMsg:'Hello! I’d like to discuss a turnkey digital solution and get a free audit.',
      leadTpl:(n,c,t)=>`Hello! My name is ${n||'—'}. Contact: ${c||'—'}. Task: ${t||'discuss a turnkey digital solution'}. I’d like a free audit and a plan.`,
      pkgTpl:p=>`Interested in the “${p}” package.`,
      mailSubject:'Lead from the SOLUTIONS site'
    },

    ru: {
      htmlLang:'ru',
      title:'SOLUTIONS — Цифровые решения под ключ | Сайты, приложения, автоматизация',
      desc:'Собираем разрозненные процессы в единое цифровое решение под ключ. Сайты, веб-приложения, автоматизация и интеграции — доступно, фиксированная цена. Бесплатный аудит и план за 3 дня.',
      hint:'листайте',
      rail:['Хаос','Фундамент','Трансформация','Цена','Старт'],
      sections:[
        {kicker:'Цифровые решения под ключ', headline:'Соберём вашу <span class="grad">систему</span> из хаоса',
         sub:'Разрозненные процессы, таблицы и сервисы — в единое цифровое решение. Под ключ, без вашего участия в технике.', extras:''},
        {kicker:'Под ключ — полный цикл', headline:'Ставите цель — <span class="grad">строим фундамент</span>',
         sub:'Аудит, архитектура, дизайн, разработка, запуск и поддержка — весь цикл на нашей стороне. Вы получаете готовый продукт, а не набор деталей.',
         extras:capsHTML([['Аудит'],['Проектирование'],['Запуск']])},
        {kicker:'Цифровая трансформация', headline:'Перестраиваем <span class="grad">бизнес</span>, а не латаем дыры',
         sub:'Автоматизируем рутину, связываем системы и данные в один контур. Меняем то, как работает компания — а не ставим софт поверх старого.',
         extras:`<div class="extras"><div class="stat reveal-extra"><div><div class="num">×3</div><div class="lbl">скорость процессов</div></div><div><div class="num">−40%</div><div class="lbl">операционных издержек</div></div></div></div>`},
        {kicker:'Доступно и прозрачно', headline:'Премиум-результат <span class="grad">без премиум-счёта</span>',
         sub:'Без раздутых смет и скрытых часов. Модульный подход и фиксированная стоимость под ключ — вы платите за результат.',
         extras:`${capsHTML([['Фиксированная стоимость','c'],['Модульно','b']])}<p class="proof reveal-extra">Под ваш рынок: <b>локальные интеграции</b>, язык и специфика — кастом, а не шаблон.</p>`},
        {kicker:'Готовы начать', final:true, headline:'Ваша система <span class="grad">собрана</span>. Запускаем?',
         sub:'Бесплатная диагностика и план трансформации за 3 дня. Покажем, как ваш хаос становится решением под ключ.',
         extras:ctaHTML({cta:'Получить план за 3 дня',cases:'Посмотреть кейсы',micro:'Бесплатно. Без обязательств.',more:'Услуги, цены и кейсы'})}
      ],
      nav:{services:'Услуги',pricing:'Цены',faq:'FAQ',wa:'Написать в WhatsApp'},
      site:{
        services:{eyebrow:'Что делаем', h2:'Цифровые решения <span class="grad">под ключ</span> — от идеи до запуска',
          lead:'Берём весь цикл на себя: вы получаете готовый работающий продукт, а не набор задач. Фиксированная стоимость, без скрытых часов.',
          cards:[['🌐','Сайты и лендинги','Продающие сайты под ключ: дизайн, разработка, запуск и аналитика.'],
                 ['⚙️','Веб-приложения и SaaS','Личные кабинеты, порталы и SaaS-продукты с нуля — под вашу бизнес-логику.'],
                 ['🔄','Автоматизация процессов','Убираем ручную рутину и Excel — процессы в одной системе, без хаоса.'],
                 ['🔌','Интеграции','Связываем CRM, ERP, платежи, мессенджеры и сервисы в единый контур.'],
                 ['🤖','Боты и AI','Telegram- и чат-боты, AI-ассистенты и автоматизация на базе LLM.'],
                 ['🛠️','Поддержка и развитие','Сопровождаем, дорабатываем и масштабируем продукт после запуска.']]},
        process:{eyebrow:'Как работаем', h2:'Прозрачный путь <span class="grad">к результату</span>',
          lead:'Никакой неопределённости: вы заранее знаете объём, сроки и стоимость.',
          steps:[['01 — БЕСПЛАТНО','Аудит','Разбираем задачу, процессы и цель. Находим, где теряются время и деньги.'],
                 ['02','Смета и план','Фиксированная стоимость и сроки. План трансформации за 3 дня.'],
                 ['03','Разработка','Дизайн → разработка → тесты. Показываем прогресс на каждом этапе.'],
                 ['04','Запуск и поддержка','Внедряем, обучаем команду, сопровождаем и развиваем.']]},
        pricing:{eyebrow:'Цены', h2:'Премиум-результат <span class="grad">без премиум-счёта</span>',
          lead:'Модульный подход и фиксированная стоимость под ключ — вы платите за результат. Точная цена — после бесплатного аудита.',
          items:[{name:'Пилот / MVP',amt:'от&nbsp;$1&nbsp;500',small:'',desc:'Быстрый старт: ключевая функция за 2–3 недели. Проверяем гипотезу на реальных пользователях.',li:['Ключевая фича','Чистый дизайн','Запуск за 2–3 недели'],btn:'Обсудить пилот',pkg:'Пилот / MVP'},
                 {name:'Проект под ключ',amt:'от&nbsp;$4&nbsp;900',small:'',desc:'Полное решение: аудит → дизайн → разработка → запуск. Берём весь цикл на себя.',li:['Аудит и стратегия','Дизайн + разработка','Интеграции под задачу','Запуск и обучение'],btn:'Получить смету',pkg:'Проект под ключ',feat:true,tag:'Популярно'},
                 {name:'Поддержка',amt:'от&nbsp;$500',small:'/мес',desc:'Развитие, доработки и сопровождение после запуска. Реагируем быстро.',li:['Доработки и фичи','Мониторинг и фиксы','Приоритетная связь'],btn:'Обсудить поддержку',pkg:'Поддержка'}],
          note:'💡 Не уверены, какой пакет нужен? Начните с <b>бесплатного аудита</b> — назовём точную цену под вашу задачу.'},
        why:{eyebrow:'Почему мы', h2:'Партнёр, а не <span class="grad">подрядчик</span>',
          items:[['🔑','Под ключ','Берём весь цикл — от аудита до поддержки. Вам не нужно вникать в технику.'],
                 ['💸','Фикс-цена','Без раздутых смет и скрытых часов. Вы платите за результат.'],
                 ['⚡','Старт за 3 дня','Бесплатный аудит и план трансформации — уже на этой неделе.'],
                 ['🌍','По всему миру','Remote-first, ваш часовой пояс и язык — кастом, а не шаблон.'],
                 ['🧩','Любая задача','Сайты, приложения, автоматизация, интеграции, боты и AI — в одном месте.'],
                 ['🤝','На связи','Прозрачный прогресс и быстрые ответы на каждом этапе проекта.']]},
        cases:{eyebrow:'Что закрываем', h2:'Примеры задач <span class="grad">под ключ</span>',
          lead:'Типовые проекты, которые мы берём. Реальные кейсы добавляем по мере запуска — есть шанс стать первым со скидкой.',
          cards:[['📊','Автоматизация продаж','CRM + интеграции + отчётность. Меньше ручной работы, прозрачная воронка.'],
                 ['🚀','Запуск онлайн-продукта','От идеи до работающего сайта или приложения под ключ — быстро и доступно.'],
                 ['🗂️','Цифровизация процессов','Учёт, заявки и документы в единой системе вместо разрозненных таблиц.']]},
        faq:{eyebrow:'Вопросы', h2:'Коротко о <span class="grad">главном</span>',
          qa:[['Сколько это стоит?','От $1 500 за пилот. Точную цену называем после бесплатного аудита — фиксом, без скрытых часов.'],
              ['Какие сроки?','Пилот — 2–3 недели. Проект под ключ — от 4–8 недель в зависимости от объёма. Сроки фиксируем в смете.'],
              ['Что значит «под ключ»?','Берём весь цикл: аудит, дизайн, разработку, запуск и поддержку. Вам не нужно вникать в технику — вы получаете готовый результат.'],
              ['А если у меня уже что-то есть?','Подключимся к текущему решению, проведём аудит и доработаем или пересоберём то, что мешает расти.'],
              ['Правки входят в стоимость?','Да, в рамках согласованного объёма. Изменения сверх — отдельной прозрачной сметой, без сюрпризов.'],
              ['Работаете по договору и NDA?','Да. Договор и NDA — по запросу. Всё прозрачно и официально.']]},
        contact:{eyebrow:'Готовы начать', h2:'Бесплатный аудит и план <span class="grad">за 3 дня</span>',
          lead:'Покажем, как ваш хаос становится решением под ключ. Бесплатно, без обязательств.',
          chips:['⚡ Ответим в течение дня','🔒 Конфиденциально','💸 Фикс-цена'],
          ph:{name:'Ваше имя',contact:'Телефон или @ник в Telegram',task:'Коротко о задаче (необязательно)'},
          submit:'Написать в WhatsApp', altPre:'или на email: ', altLink:'написать письмо',
          micro:'Нажимая кнопку, вы открываете чат с готовым сообщением — ничего не отправляется без вас.'},
        footer:{tagline:'Цифровые решения под ключ · © 2026', wa:'WhatsApp', email:'Email', top:'Наверх ↑'}
      },
      waMsg:'Здравствуйте! Хочу обсудить цифровое решение под ключ и получить бесплатный аудит.',
      leadTpl:(n,c,t)=>`Здравствуйте! Меня зовут ${n||'—'}. Контакт: ${c||'—'}. Задача: ${t||'обсудить цифровое решение под ключ'}. Хочу бесплатный аудит и план.`,
      pkgTpl:p=>`Интересует пакет «${p}».`,
      mailSubject:'Заявка с сайта SOLUTIONS'
    },

    uk: {
      htmlLang:'uk',
      title:'SOLUTIONS — Цифрові рішення під ключ | Сайти, застосунки, автоматизація',
      desc:'Збираємо розрізнені процеси в єдине цифрове рішення під ключ. Сайти, вебзастосунки, автоматизація та інтеграції — доступно, фіксована ціна. Безкоштовний аудит і план за 3 дні.',
      hint:'гортайте',
      rail:['Хаос','Фундамент','Трансформація','Ціна','Старт'],
      sections:[
        {kicker:'Цифрові рішення під ключ', headline:'Зберемо вашу <span class="grad">систему</span> з хаосу',
         sub:'Розрізнені процеси, таблиці та сервіси — в єдине цифрове рішення. Під ключ, без вашої участі в техніці.', extras:''},
        {kicker:'Під ключ — повний цикл', headline:'Ставите ціль — <span class="grad">будуємо фундамент</span>',
         sub:'Аудит, архітектура, дизайн, розробка, запуск і підтримка — весь цикл на нашому боці. Ви отримуєте готовий продукт, а не набір деталей.',
         extras:capsHTML([['Аудит'],['Проєктування'],['Запуск']])},
        {kicker:'Цифрова трансформація', headline:'Перебудовуємо <span class="grad">бізнес</span>, а не латаємо дірки',
         sub:'Автоматизуємо рутину, зв’язуємо системи та дані в один контур. Змінюємо те, як працює компанія — а не ставимо софт поверх старого.',
         extras:`<div class="extras"><div class="stat reveal-extra"><div><div class="num">×3</div><div class="lbl">швидкість процесів</div></div><div><div class="num">−40%</div><div class="lbl">операційних витрат</div></div></div></div>`},
        {kicker:'Доступно та прозоро', headline:'Преміум-результат <span class="grad">без преміум-рахунку</span>',
         sub:'Без роздутих кошторисів і прихованих годин. Модульний підхід і фіксована вартість під ключ — ви платите за результат.',
         extras:`${capsHTML([['Фіксована вартість','c'],['Модульно','b']])}<p class="proof reveal-extra">Під ваш ринок: <b>локальні інтеграції</b>, мова та специфіка — кастом, а не шаблон.</p>`},
        {kicker:'Готові почати', final:true, headline:'Ваша система <span class="grad">зібрана</span>. Запускаємо?',
         sub:'Безкоштовна діагностика та план трансформації за 3 дні. Покажемо, як ваш хаос стає рішенням під ключ.',
         extras:ctaHTML({cta:'Отримати план за 3 дні',cases:'Подивитися кейси',micro:'Безкоштовно. Без зобов’язань.',more:'Послуги, ціни та кейси'})}
      ],
      nav:{services:'Послуги',pricing:'Ціни',faq:'FAQ',wa:'Написати у WhatsApp'},
      site:{
        services:{eyebrow:'Що робимо', h2:'Цифрові рішення <span class="grad">під ключ</span> — від ідеї до запуску',
          lead:'Беремо весь цикл на себе: ви отримуєте готовий робочий продукт, а не набір задач. Фіксована вартість, без прихованих годин.',
          cards:[['🌐','Сайти та лендинги','Продавальні сайти під ключ: дизайн, розробка, запуск і аналітика.'],
                 ['⚙️','Вебзастосунки та SaaS','Особисті кабінети, портали та SaaS-продукти з нуля — під вашу бізнес-логіку.'],
                 ['🔄','Автоматизація процесів','Прибираємо ручну рутину та Excel — процеси в одній системі, без хаосу.'],
                 ['🔌','Інтеграції','Зв’язуємо CRM, ERP, платежі, месенджери та сервіси в єдиний контур.'],
                 ['🤖','Боти та AI','Telegram- і чат-боти, AI-асистенти та автоматизація на базі LLM.'],
                 ['🛠️','Підтримка та розвиток','Супроводжуємо, доопрацьовуємо та масштабуємо продукт після запуску.']]},
        process:{eyebrow:'Як працюємо', h2:'Прозорий шлях <span class="grad">до результату</span>',
          lead:'Жодної невизначеності: ви заздалегідь знаєте обсяг, терміни та вартість.',
          steps:[['01 — БЕЗКОШТОВНО','Аудит','Розбираємо задачу, процеси та ціль. Знаходимо, де втрачаються час і гроші.'],
                 ['02','Кошторис і план','Фіксована вартість і терміни. План трансформації за 3 дні.'],
                 ['03','Розробка','Дизайн → розробка → тести. Показуємо прогрес на кожному етапі.'],
                 ['04','Запуск і підтримка','Впроваджуємо, навчаємо команду, супроводжуємо та розвиваємо.']]},
        pricing:{eyebrow:'Ціни', h2:'Преміум-результат <span class="grad">без преміум-рахунку</span>',
          lead:'Модульний підхід і фіксована вартість під ключ — ви платите за результат. Точна ціна — після безкоштовного аудиту.',
          items:[{name:'Пілот / MVP',amt:'від&nbsp;$1&nbsp;500',small:'',desc:'Швидкий старт: ключова функція за 2–3 тижні. Перевіряємо гіпотезу на реальних користувачах.',li:['Ключова фіча','Чистий дизайн','Запуск за 2–3 тижні'],btn:'Обговорити пілот',pkg:'Пілот / MVP'},
                 {name:'Проєкт під ключ',amt:'від&nbsp;$4&nbsp;900',small:'',desc:'Повне рішення: аудит → дизайн → розробка → запуск. Беремо весь цикл на себе.',li:['Аудит і стратегія','Дизайн + розробка','Інтеграції під задачу','Запуск і навчання'],btn:'Отримати кошторис',pkg:'Проєкт під ключ',feat:true,tag:'Популярно'},
                 {name:'Підтримка',amt:'від&nbsp;$500',small:'/міс',desc:'Розвиток, доопрацювання та супровід після запуску. Реагуємо швидко.',li:['Доопрацювання і фічі','Моніторинг і фікси','Пріоритетний зв’язок'],btn:'Обговорити підтримку',pkg:'Підтримка'}],
          note:'💡 Не впевнені, який пакет потрібен? Почніть із <b>безкоштовного аудиту</b> — назвемо точну ціну під вашу задачу.'},
        why:{eyebrow:'Чому ми', h2:'Партнер, а не <span class="grad">підрядник</span>',
          items:[['🔑','Під ключ','Беремо весь цикл — від аудиту до підтримки. Вам не потрібно вникати в техніку.'],
                 ['💸','Фікс-ціна','Без роздутих кошторисів і прихованих годин. Ви платите за результат.'],
                 ['⚡','Старт за 3 дні','Безкоштовний аудит і план трансформації — вже цього тижня.'],
                 ['🌍','По всьому світу','Remote-first, ваш часовий пояс і мова — кастом, а не шаблон.'],
                 ['🧩','Будь-яка задача','Сайти, застосунки, автоматизація, інтеграції, боти та AI — в одному місці.'],
                 ['🤝','На зв’язку','Прозорий прогрес і швидкі відповіді на кожному етапі проєкту.']]},
        cases:{eyebrow:'Що закриваємо', h2:'Приклади задач <span class="grad">під ключ</span>',
          lead:'Типові проєкти, які ми беремо. Реальні кейси додаємо в міру запуску — є шанс стати першим зі знижкою.',
          cards:[['📊','Автоматизація продажів','CRM + інтеграції + звітність. Менше ручної роботи, прозора воронка.'],
                 ['🚀','Запуск онлайн-продукту','Від ідеї до робочого сайту чи застосунку під ключ — швидко й доступно.'],
                 ['🗂️','Цифровізація процесів','Облік, заявки та документи в єдиній системі замість розрізнених таблиць.']]},
        faq:{eyebrow:'Питання', h2:'Коротко про <span class="grad">головне</span>',
          qa:[['Скільки це коштує?','Від $1 500 за пілот. Точну ціну називаємо після безкоштовного аудиту — фіксом, без прихованих годин.'],
              ['Які терміни?','Пілот — 2–3 тижні. Проєкт під ключ — від 4–8 тижнів залежно від обсягу. Терміни фіксуємо в кошторисі.'],
              ['Що означає «під ключ»?','Беремо весь цикл: аудит, дизайн, розробку, запуск і підтримку. Вам не потрібно вникати в техніку — ви отримуєте готовий результат.'],
              ['А якщо в мене вже щось є?','Підключимося до поточного рішення, проведемо аудит і доопрацюємо або перезберемо те, що заважає рости.'],
              ['Чи входять правки у вартість?','Так, у межах узгодженого обсягу. Зміни понад — окремим прозорим кошторисом, без сюрпризів.'],
              ['Чи працюєте за договором і NDA?','Так. Договір і NDA — за запитом. Все прозоро й офіційно.']]},
        contact:{eyebrow:'Готові почати', h2:'Безкоштовний аудит і план <span class="grad">за 3 дні</span>',
          lead:'Покажемо, як ваш хаос стає рішенням під ключ. Безкоштовно, без зобов’язань.',
          chips:['⚡ Відповімо протягом дня','🔒 Конфіденційно','💸 Фікс-ціна'],
          ph:{name:'Ваше ім’я',contact:'Телефон або @нік у Telegram',task:'Коротко про задачу (необов’язково)'},
          submit:'Написати у WhatsApp', altPre:'або на email: ', altLink:'написати листа',
          micro:'Натискаючи кнопку, ви відкриваєте чат із готовим повідомленням — нічого не надсилається без вас.'},
        footer:{tagline:'Цифрові рішення під ключ · © 2026', wa:'WhatsApp', email:'Email', top:'Догори ↑'}
      },
      waMsg:'Вітаю! Хочу обговорити цифрове рішення під ключ і отримати безкоштовний аудит.',
      leadTpl:(n,c,t)=>`Вітаю! Мене звати ${n||'—'}. Контакт: ${c||'—'}. Задача: ${t||'обговорити цифрове рішення під ключ'}. Хочу безкоштовний аудит і план.`,
      pkgTpl:p=>`Цікавить пакет «${p}».`,
      mailSubject:'Заявка з сайту SOLUTIONS'
    }
  };

  window.SITE_CONTENT = CONTENT;
})();
